# Generated by Django 5.0.6 on 2024-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('Project', 'opcion_uno'), ('Job offer', 'opcion_dos')], max_length=100),
        ),
    ]
