# Generated by Django 5.0.6 on 2024-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('project', 'Project'), ('job_offer', 'Job offer')], max_length=100),
        ),
    ]
