# Generated by Django 5.0.6 on 2024-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('project', 'Project'), ('Job offer', 'job_offer')], max_length=100),
        ),
    ]
